copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\XEngine_BaseLib.dll" "./"
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\XEngine_BaseSafe.dll" "./"
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\XEngine_Algorithm.dll" "./"
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\XEngine_Core.dll" "./"
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\XEngine_ManagePool.dll" "./"
::Websocket,http need this module
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\XEngine_OPenSsl.dll" "./"
::Websocket,http need this module
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\XEngine_SystemApi.dll" "./"
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\XEngine_SystemConfig.dll" "./"
::center need this module
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\NetHelp_APIHelp.dll" "./"
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\NetHelp_XSocket.dll" "./"
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\HelpComponents_Packets.dll" "./"
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\HelpComponents_XLog.dll" "./"
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\HelpComponents_DataBase.dll" "./"
::http need this module
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\RfcComponents_HttpProtocol.dll" "./"
::websocket need this module
copy /y "D:\\XEngine\\XEngine_SourceCode\\Debug\\RfcComponents_WSProtocol.dll" "./"